kp:
  - [100, 100, 100, 100, 100, 100]
  - [100, 100, 100, 100, 100, 100]
  - [100]
  - [100, 100, 100, 100, 100]
  - [100, 100, 100, 100, 100]
  - [100]

kd:
  - [1, 1, 1, 1, 1, 1]
  - [1, 1, 1, 1, 1, 1]
  - [1]
  - [1, 1, 1, 1, 1]
  - [1, 1, 1, 1, 1]
  - [1]

# Per-joint sine parameters, grouped like joint_test.yaml
# Keep unused joints at 0.0 in target_position (amplitude)
sine:
  amplitude:
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    - [0.0]

    - [0.0, 0.0, 0.0, 0.0, 0.0]

    # - [0.0, 0.07, 0.2, 0.0, 0.0]
    - [1.0, 0.0, 0.0, 1.0, 0.0]

    - [0.0]
  frequency:
    - [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

    - [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

    - [0.5]

    - [0.5, 0.5, 0.5, 0.5, 0.5]

    - [0.5, 0.5, 0.5, 0.5, 0.5]

    - [0.5]
  phase:
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 1.57, 0.0]
    - [0.0]
  offset:
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0]
    - [0.0, 0.1, 0.0, 0.0, 0.0]
    - [0.0, -0.1, 0.0, 0.0, 0.0]
    # - [-0.3, -0.05, 1.2, -0.8, -1.5] 
    - [0.0]
  transition:
    enabled: true
    center_time: 1.0
    sharpness: 4.0
    # After this time, transition weight is forced to exactly 1.0
    settle_time: 3.0

# Common options
publish_rate: 500
num_joints: 24
